FROM node:24-alpine

RUN npm install -g pnpm turbo

WORKDIR /app

COPY package.json pnpm-lock.yaml pnpm-workspace.yaml turbo.json ./

RUN pnpm install

COPY . .

EXPOSE 3000

CMD ["pnpm", "turbo", "run", "dev", "--filter=api"]