services:
  db:
    build:
      context: .
      dockerfile: Dockerfile.db
    container_name: voyagr_db
    restart: always
    environment:
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: password
      POSTGRES_DB: voyagr
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U admin -d voyagr"]
      interval: 5s
      timeout: 5s
      retries: 5

  api:
    build:
      context: .
      dockerfile: Dockerfile.dev
    container_name: voyagr_api
    depends_on:
      db:
        condition: service_healthy
    ports:
      - "3000:3000"
    environment:
      - DATABASE_URL=postgres://admin:password@db:5432/voyagr
      - CI=true
      - BETTER_AUTH_SECRET=1234
      - BETTER_AUTH_URL=http://localhost:3000
    volumes:
      - .:/app
      - /app/node_modules
      - /app/apps/api/node_modules
      - /app/apps/web/node_modules
      - /app/packages/database/node_modules
      - /app/packages/eslint-config/node_modules
    command: sh -c "pnpm install && pnpm turbo run dev --filter=@voyagr/api"

volumes:
  postgres_data:
